"""Fence publication by current run

Revision ID: 4d5a81dcb66a
Revises: bf12fde60f45
Create Date: 2026-09-19 23:16:33.861848

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d5a81dcb66a'
down_revision: str | Sequence[str] | None = 'bf12fde60f45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('active_run_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'active_run_id')
    # ### end Alembic commands ###
