"""Persist verified starting spend

Revision ID: 6c4266208142
Revises: 4d5a81dcb66a
Create Date: 2026-09-19 23:22:00.497667

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c4266208142'
down_revision: str | Sequence[str] | None = '4d5a81dcb66a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('prior_spend', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'prior_spend')
    # ### end Alembic commands ###
