"""Initial durable workspace schema

Revision ID: bf12fde60f45
Revises:
Create Date: 2026-09-19 22:56:44.729051

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf12fde60f45'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development', sa.Integer(), nullable=False),
    sa.Column('demo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('accepted_pair', sa.JSON(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('import_digest', sa.String(length=64), nullable=True),
    sa.Column('has_mismatch', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('workflow', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('case_workspace_import', 'cases', ['workspace_id', 'import_digest'], unique=True)
    op.create_index('case_workspace_mismatch', 'cases', ['workspace_id', 'has_mismatch'], unique=False)
    op.create_index('case_workspace_received', 'cases', ['workspace_id', 'received_at'], unique=False)
    op.create_index('case_workspace_review', 'cases', ['workspace_id', 'needs_review'], unique=False)
    op.create_index(op.f('ix_cases_workspace_id'), 'cases', ['workspace_id'], unique=False)
    op.create_table('counters',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('outbox',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_run_id'), 'reservations', ['run_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_case_id'), 'runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('csrf', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_workspace_id'), 'sessions', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_expires_at'), 'workspaces', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_expires_at'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_sessions_workspace_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_case_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_reservations_run_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('counters')
    op.drop_index(op.f('ix_cases_workspace_id'), table_name='cases')
    op.drop_index('case_workspace_review', table_name='cases')
    op.drop_index('case_workspace_received', table_name='cases')
    op.drop_index('case_workspace_mismatch', table_name='cases')
    op.drop_index('case_workspace_import', table_name='cases')
    op.drop_table('cases')
    op.drop_table('budget')
    # ### end Alembic commands ###
